version: "3.3"
services:
  discord-irc.app:
    image: jekotia/discord-irc
    container_name: discord-irc.app
    restart: unless-stopped
    volumes:
    - discordirc.data.main:/data

volumes:
  discordirc.data.main:
    driver: local
    driver_opts:
      type: none
      device: ${_DISCORDIRC_DATA}
      o: bind
