version: "3.3"

services:
  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    restart: "always"
    command: "-H unix:///var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${_PORTAINER_DATA}/portainer:/data"
    networks:
      - "proxy"
    labels:
      # - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`docker.jekotia.net`)" # && PathPrefix(`/docker`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

#      - "traefik.tcp.routers.portainer.rule=HostSNI(`docker.jekotia.net`) && PathPrefix(`/api/websocket/`)"
#      - "traefik.tcp.routers.portainer.tls=true"
#      - "traefik.tcp.services.portainer.loadbalancer.server.port=9000"
