version: "3.3"

services:
  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    restart: "always"
    command: "-H unix:///var/run/docker.sock"
    volumes:
      - portainer.data.main:/data
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- shared.docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      # - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`docker.jekotia.net`)" # && PathPrefix(`/docker`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

#      - "traefik.tcp.routers.portainer.rule=HostSNI(`docker.jekotia.net`) && PathPrefix(`/api/websocket/`)"
#      - "traefik.tcp.routers.portainer.tls=true"
#      - "traefik.tcp.services.portainer.loadbalancer.server.port=9000"

volumes:
  #"${_PORTAINER_DATA}/portainer:/data"
  portainer.data.main:
    driver: local
    driver_opts:
      type: none
      device: ${_PORTAINER_DATA}/portainer
      o: bind
