version: "3.3"

services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    restart: "always"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=contact@jekotia.net"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    networks:
      - "proxy"
    environment:
      - CLOUDFLARE_EMAIL=$SECRETS_TRAEFIK_CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY=$SECRETS_TRAEFIK_CLOUDFLARE_API_KEY
    volumes:
      - traefik.data.main:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      #-> Enable the Traefik dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`mercury.jekotia.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      #-> Extras for dashboard auth
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.middlewares.auth.digestauth.users=${SECRETS_TRAEFIK_USER}:${SECRETS_TRAEFIK_REALM}:${SECRETS_TRAEFIK_PASS}"
      - "traefik.http.routers.api.middlewares=auth"

      #-> Redirect HTTP to HTTPS
      #-> https://stackoverflow.com/a/58477067/1871306
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

volumes:
  #"${_TRAEFIK_DATA}:/letsencrypt"
  traefik.data.main:
    driver: local
    driver_opts:
      type: none
      device: ${_TRAEFIK_DATA}
      o: bind
