version: "3.3"
services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud.cron:
    image: nextcloud:apache
    container_name: nextcloud.cron
    environment:
      - NEXTCLOUD_DATA_DIR=/storage
      - REDIS_HOST=nextcloud.redis
      - NEXTCLOUD_ADMIN_USER=${SECRETS_NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASS=${SECRETS_NEXTCLOUD_ADMIN_PASS}

      - MYSQL_DATABASE=${SECRETS_NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${SECRETS_NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${SECRETS_NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud.db:3306
    restart: always
    volumes:
      - nextcloud.data.storage:/storage
      - nextcloud.data.web:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud.db
      - nextcloud.redis
    networks:
      - nextcloud
