#! /bin/bash
declare -a files=(
	"discord-irc"
	#"grafana"
	"mailer"
	"ttrss"
	"wallabag"
	"weechat"
)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd ${DIR}

for file in "${files[@]}" ; do
	compose_files="${compose_files} -f $file.yml"
done

docker-compose $compose_files $@

exit
docker-compose \
	$@
