version: "3.3"
services:
  mailer:
    container_name: "mailer"
    image: "tecnativa/postfix-relay"
    restart: "always"
    environment:
    - "MAIL_RELAY_HOST=${SMTP_HOST}"
    - "MAIL_RELAY_PORT=${SMTP_PORT}"
    - "MAIL_RELAY_USER=${SMTP_USER}"
    - "MAIL_RELAY_PASS=${SMTP_PASS}"
    volumes:
    - ${_MAILER_DATA}/queue:/var/spool/postfix
    networks:
      mailer:

networks:
  mailer:
