version: "3.3"
services:
  weechat:
    image: jekotia/weechat
    container_name: weechat
    restart: "always"
    volumes:
      - ${_WEECHAT_DATA}:/data
    networks:
      - proxy
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.weechat.rule=HostSNI(`weechat.jekotia.net`)"
      - "traefik.tcp.routers.weechat.tls=true"
      - "traefik.tcp.services.weechat.loadbalancer.server.port=9001"
